name: Test generate-metadata-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  action-run:
    runs-on: ubuntu-latest
    outputs:
      filepath: ${{ steps.action-run.outputs.filepath }}
    steps:
        - name: 'Checkout directory'
          uses: actions/checkout@v2
        - name: Generate metadata file
          id: generate_metadata
          uses: 99/generate-metadata-action@main
          with:
            repository: ${{ github.event.repository.name }}
            version: make version


        - name: Set env metadata.json file location
          run:  |
            echo "$filepath"
            ls -lah

        - uses: actions/upload-artifact@v2
          with:
            name: metadata.json
            path:
          path: ${{ steps.generate_metadata.outputs.filepath }}
