name: Test generate-metadata-action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  action-run:
    runs-on: ubuntu-latest
    steps:

        - name: 'Checkout directory'
          uses: actions/checkout@v2
        - name: Generate metadata file
          id: generate_metadata
          uses: HashiCorp-RelEng-Dev/generate-metadata-action@main
          with:
            repository: ${{ github.event.repository.name }}
            filePath: "."
            versionCommand: "make version"
            filename: "metadata.json"

        - name: Print metadata.json file location
          run:  echo "The metadata.json was created in the ${{ steps.generate_metadata.outputs.filepath }}"

        - uses: actions/upload-artifact@v2
          with:
            name: metadata.json
            path: metadata.json
